name: Self-hosted runner (scheduled)


on:
#  repository_dispatch:
#  schedule:
#    - cron: "17 2 * * *"
  push:
    branches:
      - ci_with_torch_version_base
  workflow_dispatch:
    inputs:
      prev_workflow_run_id:
        description: 'previous workflow run id to compare'
        type: string
        required: false
        default: ""
      other_workflow_run_id:
        description: 'other workflow run id to compare'
        type: string
        required: false
        default: ""


env:
    prev_workflow_run_id: "eee"
    other_workflow_run_id: "ggg"


jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        run: |
          mkdir "setup_values"
          echo "${{ inputs.prev_workflow_run_id || env.prev_workflow_run_id }}" > "setup_values/prev_workflow_run_id.txt"
          echo "${{ inputs.other_workflow_run_id || env.other_workflow_run_id }}" > "setup_values/other_workflow_run_id.txt"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: setup_values
          path: setup_values

      - uses: actions/download-artifact@v4
        with:
          name: setup_values
          path: setup_values2

      - name: Prepare some setup values
        # How to use these value
        run: |
          ls -la setup_values2
          cat setup_values2/prev_workflow_run_id.txt
          cat setup_values2/other_workflow_run_id.txt

  model-ci:
    name: Model CI
    uses: ./.github/workflows/self-scheduled.yml
    with:
      job: run_models_gpu
      slack_report_channel: "#transformers-ci-daily-models"
      runner: daily-ci
      docker: huggingface/transformers-all-latest-gpu
      ci_event: Daily CI
    secrets: inherit

#  torch-pipeline:
#    name: Torch pipeline CI
#    uses: ./.github/workflows/self-scheduled.yml
#    with:
#      job: run_pipelines_torch_gpu
#      slack_report_channel: "#transformers-ci-daily-pipeline-torch"
#      runner: daily-ci
#      docker: huggingface/transformers-pytorch-gpu
#      ci_event: Daily CI
#    secrets: inherit
#
#  tf-pipeline:
#    name: TF pipeline CI
#    uses: ./.github/workflows/self-scheduled.yml
#    with:
#      job: run_pipelines_tf_gpu
#      slack_report_channel: "#transformers-ci-daily-pipeline-tf"
#      runner: daily-ci
#      docker: huggingface/transformers-tensorflow-gpu
#      ci_event: Daily CI
#    secrets: inherit
#
#  example-ci:
#    name: Example CI
#    uses: ./.github/workflows/self-scheduled.yml
#    with:
#      job: run_examples_gpu
#      slack_report_channel: "#transformers-ci-daily-examples"
#      runner: daily-ci
#      docker: huggingface/transformers-all-latest-gpu
#      ci_event: Daily CI
#    secrets: inherit
#
#  deepspeed-ci:
#    name: DeepSpeed CI
#    uses: ./.github/workflows/self-scheduled.yml
#    with:
#      job: run_torch_cuda_extensions_gpu
#      slack_report_channel: "#transformers-ci-daily-deepspeed"
#      runner: daily-ci
#      docker: huggingface/transformers-pytorch-deepspeed-latest-gpu
#      ci_event: Daily CI
#      working-directory-prefix: /workspace
#    secrets: inherit
#
#  quantization-ci:
#    name: Quantization CI
#    uses: ./.github/workflows/self-scheduled.yml
#    with:
#      job: run_quantization_torch_gpu
#      slack_report_channel: "#transformers-ci-daily-quantization"
#      runner: daily-ci
#      docker: huggingface/transformers-quantization-latest-gpu
#      ci_event: Daily CI
#    secrets: inherit
